// dados temporários
export const userColumns = [
    { field: 'id', headerName: 'ID', width: 100 },
    { field: 'product', headerName: 'Produto', width: 200 },
    { field: 'brand', headerName: 'Marca', width: 150 },
    { field: 'price', headerName: 'Preço', width: 150 },
    { field: 'stock', headerName: 'Estoque', width: 150 },
    { field: 'supplier', headerName: 'Fornecedor', width: 200},
]

 export const userRows = [
        {
            id: 1,
            product: 'Barbeador',
            brand: 'Philips',
            price: 350,
            supplier: 'Philips ltda.',  
            stock: 3,
        },
        {
            id: 2,
            product: 'Lâmina de barbear',
            brand: 'Gillette',
            price: 10,
            supplier: 'Procter & Gamble Ltda.',
            stock: 4, 
        },
        {
            id: 3,
            product: 'Pente para barba',
            brand: 'Mundial',
            price: 8,
            supplier: 'Mundial S.A.',
            stock: 20,
        },
        {
            id: 4,
            product: 'Creme de barbear',
            brand: 'Nivea',
            price: 25,
            supplier: 'Beiersdorf Indústria e Comércio Ltda.',
            stock: 15,
        },
        {
            id: 5,
            product: 'Tesoura para cabelo',
            brand: 'Wahl',
            price: 90,
            supplier: 'Wahl Clipper do Brasil Ltda.',
            stock: 10,
        },
        {
            id: 6,
            product: 'Óleo para barba',
            brand: 'Barba Brava',
            price: 30,
            supplier: 'Barba Brava Indústria e Comércio de Cosméticos Ltda.',
            stock: 25,
        },
        {
            id: 7,
            product: 'Aparador de pelos',
            brand: 'Philips',
            price: 150,
            supplier: 'Philips ltda.',
            stock: 8,
        },
        {
            id: 8,
            product: 'Loção pós-barba',
            brand: 'Nivea Men',
            price: 20,
            supplier: 'Beiersdorf Indústria e Comércio Ltda.',
            stock: 30,
        },
        {
            id: 9,
            product: 'Gel para barbear',
            brand: 'Baruel',
            price: 15,
            supplier: 'Baruel Indústria e Comércio de Cosméticos Ltda.',
            stock: 40,
        },
        {
            id: 10,
            product: 'Escova de barba',
            brand: 'Machô',
            price: 12,
            supplier: 'Machô Comércio de Produtos de Higiene Pessoal Ltda.',
            stock: 18,
        },
        {
            id: 11,
            product: 'Navalhete',
            brand: 'Solingen',
            price: 120,
            supplier: 'F. Dick GmbH & Co. KG',
            stock: 5,
        },
]